package br.com.miniagenda.formulario;

import br.com.miniagenda.bean.Contato;
import br.com.miniagenda.dao.ContatoDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Curso Técnico em Informática
 * Formulario de Exemplo
 * @author Valdinei Reis
 */
public class ContatoFormularioModelo extends javax.swing.JFrame {

    // variavel que faz a ligação desta classe, com a classe ContatoDao
    private ContatoDao contatoDao;
    
    // variavel responsavel por armazenar o ID (código) do contato
    // se o valor for 0 (zero), é porque não foi selecionado nenhum contato
    private Long idContatoSelecionado = 0L;

    /**
     * Método contrutor, responsavel por inicializar a classe
     */
    public ContatoFormularioModelo() {
        initComponents();

        preencherTabela(); // chama o método responsavel por listar os contatos
    }

    /**
     * Método responsável por preencher a tabela de contatos
     */
    private void preencherTabela() {
        List<Contato> listaDeContatos;
        try {
            // cria um novo objeto do tipo ContatoDao
            contatoDao = new ContatoDao();
            
            // chama o método 'listar', para buscar todos os contatos
            // em seguida, o resultado da busca é adicionado na variavel 
            // listaDeContatos
            listaDeContatos = contatoDao.listar();

            // trecho de código responsavel por limpar a tabela, para receber
            // novas informações
            DefaultTableModel modelo = (DefaultTableModel) tblContatos.getModel();
            modelo.setRowCount(0);

            // se a variavel 'listaDeContatos' tiver algum valor, será listado
            // todos os contatos encontrados
            if (listaDeContatos.iterator().hasNext()) {
                for (Contato contato : listaDeContatos) {
                    // pega cada contato da 'listaDeContatos' e adiciona em uma 
                    // linha da tabela
                    modelo.addRow(new Object[]{
                                contato.getId(),
                                contato.getNome(),
                                contato.getTelefone()
                            });
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao listar Contatos!\n" + ex.getMessage());
        }
    }

    /**
     * Método responsavel por limpar os campos de edição, do formulário
     */
    private void limparCampos() {
        idContatoSelecionado = 0L;

        lblAcao.setText("Adicionar Novo Contato");

        txtNome.setText("");
        txtTelefone.setText("");

        txtNome.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContatos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTelefone = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblAcao = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini Agênda");

        tblContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Telefone(s)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblContatos);

        btnEditar.setText("Editar Contato");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(java.awt.Color.lightGray);

        jLabel4.setText("Busca por Nome:");

        jButton1.setText("Buscar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEditar, btnExcluir});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar Contatos", jPanel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Telefones:");

        txtTelefone.setColumns(20);
        txtTelefone.setRows(5);
        jScrollPane2.setViewportView(txtTelefone);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jPanel5.setBackground(java.awt.Color.lightGray);

        lblAcao.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblAcao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcao.setText("Adicionar Novo Contato");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAcao, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAcao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLimpar, btnSalvar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Adicionar / Editar Contatos", jPanel2);

        jPanel3.setBackground(java.awt.Color.lightGray);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Agênda");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Sair da Mini Agênda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo Contato");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNovo, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnNovo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        // pega a linha selecionada
        Integer linha = tblContatos.getSelectedRow();

        // se o usuario nao selecionou nenhuma linha da tabela, o sistema
        // exibe uma mensagem solicitando a selecao
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um contato!");
            return;
        }

        // pega o ID do contato, com base na linha selecionada
        Long codigo = (Long) tblContatos.getValueAt(linha, 0);

        // cria um novo objeto do tipo ContatoDao
        contatoDao = new ContatoDao();
        try {

            // busca um contato pelo ID, e armazena o resultado no objeto 'contato'
            Contato contato = contatoDao.buscarPorId(codigo);

            idContatoSelecionado = contato.getId();
            txtNome.setText(contato.getNome());
            txtTelefone.setText(contato.getTelefone());

            // seleciona o segundo painel
            jTabbedPane1.setSelectedIndex(1);
            txtNome.requestFocus(); // direciona o foco para o campo txtNome

            lblAcao.setText("Alterar Contato");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao localizar Contato!\n" + ex.getMessage());
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        // pega a linha selecionada
        Integer linha = tblContatos.getSelectedRow();

        // se o usuario nao selecionou nenhuma linha da tabela, o sistema
        // exibe uma mensagem solicitando a selecao
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um contato!");
            return;
        }

        // pega o ID do contato, com base na linha selecionada
        Long codigo = (Long) tblContatos.getValueAt(linha, 0);

        // Aqui eh feito uma pergunta ao usuario, se ele deseja realmente
        // excluir o contato selecionado

        Object[] simNao = {"Sim", "Não"};
        int operacao = JOptionPane.showOptionDialog(
                null,
                "Deseja realmente excluir este Contato?",
                "Atenção",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, simNao, simNao[1]);

        // se clicou em NAO, o sistema interrompe a execucao
        if (operacao == JOptionPane.NO_OPTION) {
            return;
        }

        // cria um novo objeto do tipo ContatoDao
        contatoDao = new ContatoDao();
        try {

            // chama o método excluir, contido dentro da classe ContatoDao
            contatoDao.excluir(codigo);
            preencherTabela(); // após a exclusao, a tabela é atualizada

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir Contato!\n" + ex.getMessage());
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        limparCampos();

    }//GEN-LAST:event_btnLimparActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // trecho de código responsavel por fazer uma pergunta ao usuário
        Object[] simNao = {"Sim", "Não"};
        int operacao = JOptionPane.showOptionDialog(
                null,
                "Deseja realmente sair da Mini Agênda?",
                "Atenção",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, simNao, simNao[1]);

        // se clicou em NAO, o sistema interrompe a execucao
        if (operacao == JOptionPane.NO_OPTION) {
            return;
        }

        System.exit(0); // código responsavel por encerrar o programa
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        jTabbedPane1.setSelectedIndex(1); // Seleciona o segundo Painel

        limparCampos();

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        // Efetuar validação dos campos
        String msg = ""; // variavel que armazenará as mensagens de erro
        
        // verifica o telefone
        if (txtTelefone.getText().trim().equals("")) {
            msg += "Preencha o compo telefone.\n";
            txtTelefone.requestFocus();
        }
        // verifica o nome
        if (txtNome.getText().trim().equals("")) {
            msg += "Preencha o compo Nome.";
            txtNome.requestFocus();
        }
        
        // se a variavel 'msg' for diferente de "" (vazio) é porque 
        // ocorreu algum erro, então será exibida uma menssagem e a
        // execução do programa será interrompida
        if ( ! msg.equals("") ) {
            JOptionPane.showMessageDialog(null, msg);
            return;
        }
        
        // cria um objeto do tipo ContatoDao
        contatoDao = new ContatoDao();

        // Cria um novo contato, com os dados informados no formulário
        Contato novoContato = new Contato();
        novoContato.setId(idContatoSelecionado);
        novoContato.setNome(txtNome.getText());
        novoContato.setTelefone(txtTelefone.getText());

        try { // o try serve para capturar eventuais erros

            // se a variavel 'idContatoSelecionado' for igual a 0 (zero)
            // é porque nenhum contato foi selecionado, entao será chamado o 
            // codigo para inserir as informações no bando de dados
            if (idContatoSelecionado == 0L) {

                // código para adicionar novo contato

                contatoDao.inserir(novoContato);

                JOptionPane.showMessageDialog(null, "Contato adicionado com sucesso");

            } 
            // se a variavel 'idContatoSelecionado' for diferente de 0 (zero)
            // é porque foi selecionado algum contato na tabela, entao será 
            // chamado o código para alterar as informações gravadas no bando de dados
            else {

                // código para alterar o contato selecionado

                contatoDao.atualizar(novoContato);

                JOptionPane.showMessageDialog(null, "Contato atualizado com sucesso");

            }

            preencherTabela();
            limparCampos();

        } catch (Exception ex) {
            // caso ocorra algum problema, será exibida uma 
            // mensagem para o usuário, informando do erro
            JOptionPane.showMessageDialog(null, "Erro. Operação não realizada!\n" + ex.getMessage());
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ContatoFormularioModelo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAcao;
    private javax.swing.JTable tblContatos;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtTelefone;
    // End of variables declaration//GEN-END:variables
}
